# Generated by Django 3.2 on 2022-06-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('wardrobes', 'ШКАФ'), ('bedroom-sets', 'СПАЛЬНИ'), ('hallways', 'ПРИХОЖИЕ'), ('kitchens', 'КУХНИ'), ('tv-stand', 'TV ТУМБЫ'), ('dressers', 'КОМОДЫ'), ('living-room-sets', 'ГОСТИНЫЕ'), ('children-sets', 'ДЕТСКИЕ & ОФИС'), ('cushioned-furniture', 'МЯГКАЯ МЕБЕЛЬ')], default='cupboard', max_length=150),
        ),
    ]
