# Generated by Django 3.2 on 2022-06-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220617_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('wardrobes', 'ШКАФ'), ('bedroom-sets', 'СПАЛЬНИ'), ('hallways', 'ПРИХОЖИЕ'), ('kitchens', 'КУХНИ'), ('tv-stand', 'TV ТУМБЫ'), ('dressers', 'КОМОДЫ'), ('living-room-sets', 'ГОСТИНЫЕ'), ('children-sets', 'ДЕТСКИЕ & ОФИС'), ('cushioned-furniture', 'МЯГКАЯ МЕБЕЛЬ')], default='cupboard', max_length=255),
        ),
    ]
