# Generated by Django 3.2 on 2022-06-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220620_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscription',
            new_name='is_subscribed',
        ),
    ]
