# Generated by Django 3.2 on 2022-06-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cart.shoppingcart'),
        ),
    ]
